name: Publish Gem
 
 on:
   release:
     types: [released]
 
 jobs:
   release:
     runs-on: macOS-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Setup Ruby
         uses: ruby/setup-ruby@v1
         with:
           ruby-version: '2.7.8'
       - name: Build gem
         run: |
           gem build github-pages.gemspec
       - name: Publish
         run: |
           gem push github-pages.gem --key ${{ secrets.PAGES_GEM_PUBLISH }}
    test:
    runs-on: [self-hosted, "${{ inputs.chosen-os }}"]
    steps:
    - run: echo Hello world!       